name = "recuperacao-vendas"
main = "src/worker.js"
compatibility_date = "2024-06-01"

routes = [
  { pattern = "/webhook", script = "src/worker.js" }
]

[[queues.producers]]
binding = "RECUPERACAO_QUEUE"
queue = "recuperacao-vendas"

[[queues.consumers]]
queue = "recuperacao-vendas"
max_batch_size = 10
max_batch_timeout = 30
script = "src/queue-consumer.js"

[vars]
GUPSHUP_APIKEY = "sua_apikey"
GUPSHUP_SOURCE = "seu_numero"
